### ISSUE TITLE
I can't open a VP9 .ivf file ?

### ISSUE THREAD

**Issue by dumenil** [mbebenita/aomanalyzer#9]
http://aomanalyzer.org/?
Hi, I can't open a VP9 .ivf file ? Is it normal ?
thanks

**Comment by mbebenita** [comment]
VP9 files are not supported, only the latest versions of AV1 .ivf files can be opened.

**Comment by mbebenita** [comment]
The latest version of the analyzer is now part of www.arewecompressedyet.com. For example:

https://arewecompressedyet.com/analyzer.html?maxFrames=4&decoder=https://arewecompressedyet.com/runs/ll4-cdef-strength08@2017-02-28T23:44:54.065Z/js/decoder.js&file=https://arewecompressedyet.com/runs/ll4-cdef-strength08@2017-02-28T23:44:54.065Z/objective-1-fast/Netflix_FoodMarket_1920x1080_60fps_8bit_420_60f.y4m-63.ivf

**Comment by mbebenita** [comment]
I ported the analyzer to vp9 as well, you should be able to load `*.ivf` files now. 

`http://aomanalyzer.org/awcy/analyzer.html?decoder=decoder-vp9.js&file=default-vp9.ivf`

Instead of default-vp9.ivf, specify an URL where CORS is enabled.

**Comment by dumenil** [comment]
Hi ,
Thanks a lot Michael.
I’ve just tried but it doesn’t work yet. The analyzer is just saying “Downloading Files” with the wheel turning.  Perhaps my vp9.ivf is not correct. Up to now I do not know how to enable CORS. I have to check. Is it possible to get vp9.ivf file ?

Thanks a lot
Patrick

**Comment by mbebenita** [comment]
One thing you can try is to set up a local server using:

```
pyhon -m SimpleHTTPServer
```

and then make the analyzer point to it

```
http://aomanalyzer.org/awcy/analyzer.html?decoder=decoder-vp9.js&file=localhost:8000/vp9.ivf
```

**Comment by mbebenita** [comment]
Can you share your `.ivf` file? I've only tested on my own files.

**Comment by dumenil** [comment]
Hi Michael,
Here is my file attached. It is a UHD VP9. The stream can be played with ffmpeg.
Perhaps my ivf encaps is bad ?
Thanks a lot
Patrick

**Comment by mbebenita** [comment]
@dumenil you'll need to attach the file directly in this github issue, not by responding using email. I think the attachments are being dropped.

**Comment by dumenil** [comment]
here is the vp9 ivf file 

[crowdrun_vp9.zip](https://github.com/mbebenita/aomanalyzer/files/820534/crowdrun_vp9.zip)
I

**Comment by dumenil** [comment]
[crowdrun_vp9.zip](https://github.com/mbebenita/aomanalyzer/files/820537/crowdrun_vp9.zip)

**Comment by dumenil** [comment]
Ok , I have attached the file directly to the github.

**Comment by mbebenita** [comment]
This appears to work:

http://aomanalyzer.org/awcy/analyzer.html?decoder=decoder-vp9.js&file=crowdrun_vp9.ivf

I think it's just an issue with how you are specifying the URL to `crowdrun_vp9.ivf`. Another thing you can try is to use the analyzer in `local` mode. 

http://aomanalyzer.org/awcy/analyzer.html?local=1

Then, drag both the `decoder-vp9.js` and `crowdrun_vp9.ivf` files (at the same time) on the first square, then click Analyzer. You can download the `.js` file from, http://aomanalyzer.org/awcy/decoder-vp9.js
