### ISSUE TITLE
-

### ISSUE THREAD

**Issue by ghost** [mbebenita/aomanalyzer#96]

**Comment by vibhoothi** [comment]
It is been sometime since it is maintained and made it working with modern JS versions, so seems to be existed, but when I tried few months back I was able to get it work when I used pinned version. 

Do let us know if you face any compile issues, we can try to fix it.

**Comment by vibhoothi** [comment]
Sure, but without information on current issue, I am not sure how to help you, please do post full information on the issue you facing, so we can try to do fix it, without more information it would be difficult to help.

**Comment by LuisB79** [comment]
Will do.

**Comment by LuisB79** [comment]
i'll make an apropiate issue later
